### ISSUE TITLE
Demo script not working

### ISSUE THREAD

**Issue by natitaye** [guanlongzhao/ppg-gmm#1]
Hi,

I installed all the necessary packages and set up all the configuration files accoriding to the instructions provided. However, when I run the demo file `demo.m`, I'm getting this error while the script is trying to build a GMM model:

Reference to non-existent field 'post'.

Error in prepareDataGMM (line 54)
        temppost = utts(ii).post(:, keepIdx);

Error in buildGMMmodelGSB (line 103)
    [concSrcMcep, srcPost] = prepareDataGMM(srcUtts);

Error in demo (line 76)
[gmmMdlPath, gmmStatus] = buildGMMmodelGSB(srcTrainSet, tgtTrainSet,...
 
Am I missing something here?

**Comment by guanlongzhao** [comment]
Resolved offline... This was probably because the PPG extraction failed.
