### ISSUE TITLE
error while running preparefixturefortests.m

### ISSUE THREAD

**Issue by snehasingh30** [guanlongzhao/ppg-gmm#2]
After running the preparefixturefortests.m, i am getting these errors in matlab: 
 
Error using dataPrep (line 127)
The value of 'NumWorkers' is invalid. It must satisfy the function:
@(x)x>=0&&x<=maxWorkers.

Error in prepareFixturesForTests (line 30)
matList = dataPrep(wavList, transFile, fullfile(rootDir, 'src/cache'),...

**Comment by guanlongzhao** [comment]
I think it has something to do with the parallel toolbox... If you do not have the parallel toolbox you can just set https://github.com/guanlongzhao/ppg-gmm/blob/master/function/dataPrep.m#L127 to 0, which will run the function on one worker... Let me know if it works.

**Comment by snehasingh30** [comment]
> I think it has something to do with the parallel toolbox... If you do not have the parallel toolbox you can just set https://github.com/guanlongzhao/ppg-gmm/blob/master/function/dataPrep.m#L127 to 0, which will run the function on one worker... Let me know if it works.

Still after doing this it's showing the same error.
but when i also change line 30 as  matList = dataPrep(wavList, transFile, fullfile(rootDir, 'src/cache'),...
    'NumWorkers', 0); in prefparefixturefortests.m then i run into other issue as below even when the prompts.txt is present at the location.
Error using dataPrep (line 181)
Transcription file home/ss3001/ppg-gmm/test/data/src/prompts.txt does
not exist.

Error in prepareFixturesForTests (line 30)
matList = dataPrep(wavList, transFile, fullfile(rootDir,
'src/cache'),...

Please guide for the same.

**Comment by guanlongzhao** [comment]
Which Matlab version and OS are you using? Can you also copy the log file under `test/data/src/cache` so I can see what's happening there? The log file should look like `log_xxx`.

**Comment by snehasingh30** [comment]
> Which Matlab version and OS are you using? Can you also copy the log file under `test/data/src/cache` so I can see what's happening there? The log file should look like `log_xxx`.

I am using Matlab R2019a and OS Ubuntu 16.04 on VMware. Sir, I don't have folder cache in 'test/data/src'. Please guide. Thank You.

**Comment by guanlongzhao** [comment]
Hmm, so this might be an I/O issue. Please make sure you have rw permission on the disk you are operating on. Also take a look at https://github.com/guanlongzhao/ppg-gmm/blob/master/function/dataPrep.m#L135, this should create `src/cache` when calling it from https://github.com/guanlongzhao/ppg-gmm/blob/master/script/prepareFixturesForTests.m#L30. See if you can run https://github.com/guanlongzhao/ppg-gmm/blob/master/function/dataPrep.m#L135 outside of all the other parts of the function (e.g.,  in a Matlab workspace)

**Comment by snehasingh30** [comment]
> Which Matlab version and OS are you using? Can you also copy the log file under `test/data/src/cache` so I can see what's happening there? The log file should look like `log_xxx`.

Below are the log files attached. Can you please guide me on how shall I proceed further and what error I am making? Please check in the attachment below if I have rightly set KALDI_ROOT in dependency/kaldi-posteriorgram/path.sh or not.
Thank you.
![1](https://user-images.githubusercontent.com/61877380/93621035-9a0d7400-f9f8-11ea-834b-94c8242f463e.PNG)
![2](https://user-images.githubusercontent.com/61877380/93621040-9b3ea100-f9f8-11ea-97e4-f3edcc4ef422.PNG)
![3](https://user-images.githubusercontent.com/61877380/93621043-9da0fb00-f9f8-11ea-82fa-8ea457b81b3f.PNG)
[log_20200809T010534.txt](https://github.com/guanlongzhao/ppg-gmm/files/5246751/log_20200809T010534.txt)
[log_20200809T021653.txt](https://github.com/guanlongzhao/ppg-gmm/files/5246753/log_20200809T021653.txt)
[log_20200809T010224.txt](https://github.com/guanlongzhao/ppg-gmm/files/5246754/log_20200809T010224.txt)
[log_20200809T010534.txt](https://github.com/guanlongzhao/ppg-gmm/files/5246756/log_20200809T010534.txt)
[log_20200809T020712.txt](https://github.com/guanlongzhao/ppg-gmm/files/5246757/log_20200809T020712.txt)

**Comment by guanlongzhao** [comment]
> > Which Matlab version and OS are you using? Can you also copy the log file under `test/data/src/cache` so I can see what's happening there? The log file should look like `log_xxx`.
> 
> Below are the log files attached. Can you please guide me on how shall I proceed further and what error I am making? Please check in the attachment below if I have rightly set KALDI_ROOT in dependency/kaldi-posteriorgram/path.sh or not.
> Thank you.
> ![1](https://user-images.githubusercontent.com/61877380/93621035-9a0d7400-f9f8-11ea-834b-94c8242f463e.PNG)
> ![2](https://user-images.githubusercontent.com/61877380/93621040-9b3ea100-f9f8-11ea-97e4-f3edcc4ef422.PNG)
> ![3](https://user-images.githubusercontent.com/61877380/93621043-9da0fb00-f9f8-11ea-82fa-8ea457b81b3f.PNG)
> [log_20200809T010534.txt](https://github.com/guanlongzhao/ppg-gmm/files/5246751/log_20200809T010534.txt)
> [log_20200809T021653.txt](https://github.com/guanlongzhao/ppg-gmm/files/5246753/log_20200809T021653.txt)
> [log_20200809T010224.txt](https://github.com/guanlongzhao/ppg-gmm/files/5246754/log_20200809T010224.txt)
> [log_20200809T010534.txt](https://github.com/guanlongzhao/ppg-gmm/files/5246756/log_20200809T010534.txt)
> [log_20200809T020712.txt](https://github.com/guanlongzhao/ppg-gmm/files/5246757/log_20200809T020712.txt)

The KALDI_ROOT path looks fine, just double check that the referred files exist.

Based on the other logs I would suggest resetting your `test/data` dir by deleting the existing content and downloading a clean copy from this repo.

**Comment by snehasingh30** [comment]
sir i have reset test/data dir but still the error is not solved. I am
attaching the log file below.

**Comment by guanlongzhao** [comment]
You can try running the script line-by-line and try to read the code and see if you can find a fix. This is how I usually do to debug this software.
